### ISSUE TITLE
Report bundle size

### ISSUE THREAD

**Issue by delphiactual** [packtracker/webpack-plugin#10]
It would be great if bundle size was reported, and the change from the last commit.

**Comment by jondavidjohn** [comment]
I believe we do this right? For example...

https://github.com/DestinyItemManager/DIM/pull/4218/checks?check_run_id=223072422

**Comment by delphiactual** [comment]
It should be reporting a major downsize in `main.js` 3.16MB vs 4.33MB
https://app.packtracker.io/organizations/159/projects/136/commits/d2f09c118a62494e0ebf895a70ee64e63500b2ff/explore

vs 

https://app.packtracker.io/organizations/159/projects/136/commits/17e8cc17e72b3645e0f4bb699469b4519ae21e7f/explore

**Comment by jondavidjohn** [comment]
Sorry, I'm not quite following, the links you are showing show a `main.js` at 1.35 and 1.33 MB which is what the PRs reflect?

**Comment by delphiactual** [comment]
I guess it's a misunderstanding about what bundle explorer shows and what is displayed on the PR
