### ISSUE TITLE
Add CodeSandbox CI detection

### ISSUE THREAD

**Issue by yesmeck** [packtracker/webpack-plugin#12]
This plugin will now fail to run on CodeSandbox CI, It would be nice to add a detection for CodeSandbox CI.

See this build log https://ci.codesandbox.io/status/ant-design/ant-design/pr/19721/builds/1310

cc @CompuIves

**Comment by jondavidjohn** [comment]
Thanks @yesmeck, it looks like from the error that this describes the issue fairly well.

https://docs.packtracker.io/faq#why-cant-the-plugin-determine-my-branch-name

You could either 

1) Print all environment variables (with `env`) for your CI environment, and see if there is one containing the branch name that you could pass along to the plugin.

2) GitHub Actions are releasing today, so you could try and use that instead.
