### ISSUE TITLE
Gracefully fail without Git

### ISSUE THREAD

**Issue by SimenB** [packtracker/webpack-plugin#5]
If it command fails, it would be nice if you printed out what you tried to use git to find. I had a yupo in the config I passed in, which caused the plugin to try to invoke git. Similar to #4 it's not a git repo, so even if the git binary was there, it would have failed

**Comment by jondavidjohn** [comment]
Good idea, better handling of this case is released with `2.1.0`

https://github.com/packtracker/webpack-plugin/blob/develop/config.js#L67-L75
